name: market-speed
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anyio=4.12.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h80b0991_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.0=h7b7b1db_16
  - aws-c-cal=0.9.2=h6f29d6d_1
  - aws-c-common=0.12.4=h1c43f85_0
  - aws-c-compression=0.3.1=h7a4e982_6
  - aws-c-event-stream=0.5.5=he80c2a0_1
  - aws-c-http=0.10.2=h5393f03_3
  - aws-c-io=0.21.0=h46f635e_1
  - aws-c-mqtt=0.13.1=h14d32e2_4
  - aws-c-s3=0.8.3=hee7c3f6_1
  - aws-c-sdkutils=0.2.4=h7a4e982_1
  - aws-checksums=0.2.7=h7a4e982_2
  - aws-crt-cpp=0.32.10=hdb1ac85_3
  - aws-sdk-cpp=1.11.510=h406418f_14
  - azure-core-cpp=1.14.0=h9a36307_0
  - azure-identity-cpp=1.10.0=ha4e2ba9_0
  - azure-storage-blobs-cpp=12.13.0=h3d2f5f1_1
  - azure-storage-common-cpp=12.8.0=h1ccc5ac_1
  - azure-storage-files-datalake-cpp=12.12.0=h86941f0_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli=1.1.0=h1c43f85_4
  - brotli-bin=1.1.0=h1c43f85_4
  - brotli-python=1.1.0=py312h462f358_4
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.6=hb5e19a0_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312he90777b_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312hd099df3_3
  - cpython=3.12.12=py312hd8ed1ab_1
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.18=py312hbfd3414_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=heffb93a_0
  - fonttools=4.61.1=py312hacf3034_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h694c41f_0
  - gflags=2.2.2=hac325c4_1005
  - glog=0.7.1=h2790a97_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py312h90e26e8_2
  - krb5=1.21.3=h37d8d59_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20250127.1=cxx17_h0e468a2_0
  - libarrow=17.0.0=hcc79438_62_cpu
  - libarrow-acero=17.0.0=hdc53af8_62_cpu
  - libarrow-dataset=17.0.0=hdc53af8_62_cpu
  - libarrow-substrait=17.0.0=ha37b807_62_cpu
  - libblas=3.11.0=5_he492b99_openblas
  - libbrotlicommon=1.1.0=h1c43f85_4
  - libbrotlidec=1.1.0=h1c43f85_4
  - libbrotlienc=1.1.0=h1c43f85_4
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.17.0=h7dd4100_1
  - libcxx=21.1.8=h3d58e20_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgcc=15.2.0=h08519bb_15
  - libgfortran=15.2.0=h7e5c614_15
  - libgfortran5=15.2.0=hd16e46c_15
  - libgoogle-cloud=2.36.0=h777fda5_1
  - libgoogle-cloud-storage=2.36.0=h3397294_1
  - libgrpc=1.71.0=h7d722e6_1
  - libiconv=1.18=h57a12c2_2
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.11.0=5_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - liblzma-devel=5.8.1=hd471939_2
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libparquet=17.0.0=h283e888_62_cpu
  - libpng=1.6.53=h380d223_0
  - libprotobuf=5.29.3=h3209144_3
  - libre2-11=2025.06.26=hfc00f1c_0
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.51.1=hb99441e_1
  - libssh2=1.11.1=hed3591d_0
  - libthrift=0.21.0=h75589b3_0
  - libtiff=4.7.1=ha0a348c_1
  - libutf8proc=2.10.0=h5b79583_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.13.9=hc5750cf_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.8=h472b3d1_0
  - lz4-c=1.10.0=h240833e_1
  - markupsafe=3.0.3=py312hacf3034_0
  - matplotlib=3.8.4=py312hb401068_2
  - matplotlib-base=3.8.4=py312hb6d62fa_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.5.1=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py312he3a82b2_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.6.0=h230baf5_0
  - orc=2.1.2=h82caab2_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.2=py312h1171441_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py312hea0c9db_2
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.2.1=py312hf7082af_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=17.0.0=py312h0be7463_2
  - pyarrow-core=17.0.0=py312h5157fe3_2_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.1=py312h4a480f0_0
  - pyobjc-framework-cocoa=12.1=py312h1993040_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=h74c2667_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2024.2=pyhd8ed1ab_1
  - pyyaml=6.0.3=py312hacf3034_0
  - pyzmq=27.1.0=py312hb7d603e_0
  - re2=2025.06.26=ha5e900a_0
  - readline=8.3=h68b038d_0
  - referencing=0.37.0=pyhcf101f3_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py312h8a6388b_0
  - scikit-learn=1.5.2=py312h9d777eb_1
  - scipy=1.15.2=py312hd04560d_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h01f5ddf_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - sqlite=3.51.1=h5af3ad2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.2=py312h5dc8b90_0
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=hf689a15_3
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.3=py312h80b0991_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py312h80b0991_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - xz=5.8.1=h357f2ed_2
  - xz-gpl-tools=5.8.1=h357f2ed_2
  - xz-tools=5.8.1=hd471939_2
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hd23fc13_2
  - zlib-ng=2.3.2=h8bce59a_1
  - zstandard=0.25.0=py312h01f6755_1
  - zstd=1.5.7=h3eecb57_6
  - pip:
      - appdirs==1.4.4
      - exchange-calendars==4.11.3
      - frozendict==2.4.7
      - html5lib==1.1
      - korean-lunar-calendar==0.3.1
      - lxml==6.0.2
      - multitasking==0.0.12
      - pandas-datareader==0.10.0
      - pandas-market-calendars==4.4.1
      - peewee==3.18.3
      - pyluach==2.3.0
      - requests==2.32.3
      - toolz==1.1.0
      - yfinance==0.2.38

